// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJFsOKFpeXUCWZEf3jFKfOmMkT9GwSzYA',
    appId: '1:615638819825:web:4c19657486a8bccba39a50',
    messagingSenderId: '615638819825',
    projectId: 'calcam-ff4a3',
    authDomain: 'calcam-ff4a3.firebaseapp.com',
    storageBucket: 'calcam-ff4a3.appspot.com',
    measurementId: 'G-YC788X3W6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGn_YzrM-E2cBiX7jvlE1lKLICr-ZvGM',
    appId: '1:615638819825:android:9e61920ab97d40a8a39a50',
    messagingSenderId: '615638819825',
    projectId: 'calcam-ff4a3',
    storageBucket: 'calcam-ff4a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhTw4FYzznECXkq54R9JmX-rDghoc5J4',
    appId: '1:615638819825:ios:2100d8ed7bffcc37a39a50',
    messagingSenderId: '615638819825',
    projectId: 'calcam-ff4a3',
    storageBucket: 'calcam-ff4a3.appspot.com',
    iosBundleId: 'com.example.calCam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOhTw4FYzznECXkq54R9JmX-rDghoc5J4',
    appId: '1:615638819825:ios:2100d8ed7bffcc37a39a50',
    messagingSenderId: '615638819825',
    projectId: 'calcam-ff4a3',
    storageBucket: 'calcam-ff4a3.appspot.com',
    iosBundleId: 'com.example.calCam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJFsOKFpeXUCWZEf3jFKfOmMkT9GwSzYA',
    appId: '1:615638819825:web:2ea2ca28cbed521aa39a50',
    messagingSenderId: '615638819825',
    projectId: 'calcam-ff4a3',
    authDomain: 'calcam-ff4a3.firebaseapp.com',
    storageBucket: 'calcam-ff4a3.appspot.com',
    measurementId: 'G-SELC85QCD0',
  );
}
